import React from "react";
import Head from "next/head";
import Image from "next/image";
import useOnScreen from "../hooks/useOnScreen";

const IndexPage = () => {
  const refDate = React.useRef();
  const dateOnScreen = useOnScreen(refDate, "-70px");
  const refText = React.useRef();
  const textOnScreen = useOnScreen(refText, "-100px");
  return (
    <>
      <Head>
        <title>Pietro e Marta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container ">
        <div className="pic-container appear">
          <Image
            src="/pietro-w.png"
            alt="pietro"
            width={350}
            height={420}
            className="moving"
          />
          <Image
            src="/marta-w-svg.svg"
            alt="marta"
            width={350}
            height={420}
            className="moving"
          />
        </div>
        <div className="title appear" style={{ "--delay": "1s" }}>
          <h1>
            Pietro
            <span style={{ margin: "0 2rem" }}>e</span> Marta
          </h1>
          <h1>
            <b>OGGI SPOSI!</b>
          </h1>
        </div>
        <div
          className="date "
          ref={refDate}
          style={{
            height: 180,
          }}
        >
          {dateOnScreen && (
            <div className="jump">
              <i className="appear">19 Giugno 2022</i>
            </div>
          )}
        </div>
        <section
          className="text"
          ref={refText}
          style={{
            height: 590,
          }}
        >
          {textOnScreen && (
            <article className="jump">
              <p className="appear">
                Oggi finalmente si celebra il matrimonio tra Marta e Pietro! Un
                evento atteso da anni ormai!...troppi anni, così tanti che
                eravamo giá pronti a celebrare le loro nozze d'argento!! Potete
                crederci?
              </p>
              <p className="appear">Ebbene si!</p>
              <p className="appear">
                I nostri cari amici finalmente sono riusciti ad allineare i
                pianeti, annullare le macumbe, radunare le fattucchiere piú
                potenti tra tutte le tribù africane conosciute fino ad ora e le
                hanno pregate ti rendere possibile l'organizzazione di tale
                evento!
              </p>
            </article>
          )}
        </section>
        <section className="animated-pics">
          <div>
            <Image
              src="/pietro-w-smile.png"
              alt="pietro"
              width={350}
              height={420}
              className="alternate-A"
            />
          </div>
          <div>
            <Image
              src="/pietro-w.png"
              alt="pietro"
              width={350}
              height={420}
              className="alternate-B"
            />
          </div>
        </section>
      </div>
    </>
  );
};
export default IndexPage;

// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/pietro-w.png" alt="pietro" width={350} height={420} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
